"""Core analysis package for MorphoStack."""

from morphostack.core.contours import (
    SegmentationPreview,
    contour_circularity,
    largest_component_boundary,
    largest_connected_component,
    largest_opencv_contour,
    segmentation_preview,
    smooth_contour_guarded,
)
from morphostack.core.export import (
    CSV_COLUMNS,
    BATCH_SUMMARY_COLUMNS,
    analysis_report_markdown,
    analysis_manifest,
    analysis_rows,
    analysis_run_warnings,
    analysis_summary_row,
    analysis_summary,
    analysis_warnings,
    failed_analysis_summary_row,
    write_batch_summary_csv,
    write_analysis_csv,
    write_analysis_manifest_json,
    write_analysis_report_markdown,
)
from morphostack.core.images import as_color_stack, as_grayscale_stack, stretch_to_uint8
from morphostack.core.io import file_sha256, load_image_stack, inspect_image_stack
from morphostack.core.mesh import (
    MeshMeasurement,
    contour_to_mask,
    contour_stack_mesh_geometry,
    contours_to_mask_stack,
    measure_contour_stack,
    surface_area_volume,
    write_mesh_file,
    write_mesh_obj,
    write_mesh_ply,
    write_mesh_stl,
)
from morphostack.core.metrics import ContourMetrics, contour_metrics
from morphostack.core.models import ImageStack, VoxelSize
from morphostack.core.pipeline import (
    FrameAnalysis,
    FrameTrackingRecord,
    ObjectSeed,
    SeedPoint,
    RectROI,
    StackAnalysis,
    StackViewTransform,
    TrackingDiagnostics,
    ZRange,
    analyze_frame,
    analyze_stack,
    object_seed_payload,
    tracking_diagnostics_payload,
)
from morphostack.core.project import (
    PROJECT_SETTINGS_VERSION,
    ProjectSettings,
    SweepSettings,
    load_project_settings,
    write_project_settings,
)
from morphostack.core.profiles import DEFAULT_PROFILE, PROFILE_CHOICES, AnalysisProfile, normalize_profile
from morphostack.core.segmentation import apply_rect_roi, apply_z_range, suggest_threshold, threshold_mask
from morphostack.core.sweep import (
    SWEEP_COLUMNS,
    ThresholdSweepResult,
    best_sweep_result,
    threshold_sweep,
    threshold_sweep_rows,
    threshold_values,
    write_threshold_sweep_csv,
)
from morphostack.core.validation import (
    ValidationDifference,
    ValidationReport,
    compare_metric_csv,
    format_validation_report,
)

__all__ = [
    "AnalysisProfile",
    "BATCH_SUMMARY_COLUMNS",
    "ContourMetrics",
    "CSV_COLUMNS",
    "DEFAULT_PROFILE",
    "FrameAnalysis",
    "FrameTrackingRecord",
    "ImageStack",
    "MeshMeasurement",
    "ObjectSeed",
    "SeedPoint",
    "PROFILE_CHOICES",
    "PROJECT_SETTINGS_VERSION",
    "ProjectSettings",
    "RectROI",
    "SegmentationPreview",
    "StackAnalysis",
    "StackViewTransform",
    "TrackingDiagnostics",
    "SWEEP_COLUMNS",
    "SweepSettings",
    "ThresholdSweepResult",
    "VoxelSize",
    "ZRange",
    "ValidationDifference",
    "ValidationReport",
    "apply_rect_roi",
    "apply_z_range",
    "as_color_stack",
    "as_grayscale_stack",
    "analyze_frame",
    "analyze_stack",
    "analysis_manifest",
    "analysis_report_markdown",
    "analysis_rows",
    "analysis_run_warnings",
    "analysis_summary",
    "analysis_summary_row",
    "analysis_warnings",
    "best_sweep_result",
    "contour_circularity",
    "contour_metrics",
    "contour_to_mask",
    "contours_to_mask_stack",
    "compare_metric_csv",
    "failed_analysis_summary_row",
    "file_sha256",
    "format_validation_report",
    "largest_component_boundary",
    "largest_connected_component",
    "largest_opencv_contour",
    "load_project_settings",
    "inspect_image_stack",
    "load_image_stack",
    "measure_contour_stack",
    "contour_stack_mesh_geometry",
    "normalize_profile",
    "object_seed_payload",
    "tracking_diagnostics_payload",
    "segmentation_preview",
    "smooth_contour_guarded",
    "stretch_to_uint8",
    "surface_area_volume",
    "write_mesh_file",
    "write_mesh_obj",
    "write_mesh_ply",
    "write_mesh_stl",
    "suggest_threshold",
    "threshold_sweep",
    "threshold_sweep_rows",
    "threshold_values",
    "threshold_mask",
    "write_batch_summary_csv",
    "write_analysis_csv",
    "write_analysis_manifest_json",
    "write_analysis_report_markdown",
    "write_project_settings",
    "write_threshold_sweep_csv",
]
